### PR TITLE
Single release hijacked packet on Bungee

### LINKED ISSUE #325: Bug Report: Potential memory leak on BungeeCord
### General information

Sonar's custom decoder seems to leak a bit of memory on BungeeCord servers:
```
22:07:14 [SEVERE] LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
```

This does not happen on Velocity proxies.

### Steps to reproduce

1. Start your BungeeCord proxy with the JVM arguments `-Dio.netty.leakDetection.level=PARANOID`

### Sonar dump

/

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by FallenCrystal**
Resolves #325 

After our hijacking, we should release byteBuf in PacketWrapper. Because this was supposed to be release by the HandlerBoss.

`trySingleRelease` does not release a second times. This should be safe.

Also replace the original `CHANNEL_WRAPPER_FIELD` field with MethodHandle.

### CODE REVIEW

**Comment by jonesdevelopment** [comment]
This actually fixes it?

File: sonar-bungee/src/main/java/xyz/jonesdev/sonar/bungee/fallback/FallbackChannelHandler.java [hunk 1]
```diff
@@ -40,12 +41,13 @@ public FallbackChannelHandler(final @NotNull Channel channel) {
...
 
-  private static final Field CHANNEL_WRAPPER_FIELD;
+  private static final MethodHandle CHANNEL_WRAPPER_GETTER;
 
   static {
     try {
-      CHANNEL_WRAPPER_FIELD = HandlerBoss.class.getDeclaredField("channel");
-      CHANNEL_WRAPPER_FIELD.setAccessible(true);
+      CHANNEL_WRAPPER_GETTER = MethodHandles
+        .privateLookupIn(HandlerBoss.class, MethodHandles.lookup())
```
Comment (jonesdevelopment) [inline sonar-bungee/src/main/java/xyz/jonesdev/sonar/bungee/fallback/FallbackChannelHandler.java]: Please use the same codestyle as here: <https://github.com/jonesdevelopment/sonar/blob/main/sonar-velocity/src/main/java/xyz/jonesdev/sonar/velocity/fallback/FallbackChannelInitializer.java#L38>

**Comment by jonesdevelopment** [comment]
I'll try this out right now. Thanks a lot for this PR!

**Comment by FallenCrystal** [comment]
> This actually fixes it?

For me, yes. But it's not clear to me if this will work properly on forks on modified decoders like FlameCord.

**Comment by jonesdevelopment** [comment]
I know most forks use `copy` instead of `slice` in the `MinecraftDecoder` class. However, that should not interfere with `trySingleRelease`?

**Comment by jonesdevelopment** [comment]
If somebody modifies the decoder/releasing logic, they must also change the way `trySingleRelease` works without breaking the entire API, so I believe it's fine merging this PR. What do you think? I want to go to sleep. x)

**Comment by jonesdevelopment** [comment]
I'll ask somebody who uses FlameCord to test it. I'll check back on this tomorrow.

**Comment by FallenCrystal** [comment]
> I know most forks use `copy` instead of `slice` in the `MinecraftDecoder` class. However, that should not interfere with `trySingleRelease`?

It is unclear if this will result in a secondary release. But I don't have a FlameCord. heard from [here](https://github.com/Exceptionflug/protocolize/issues/226#issuecomment-1913189607).

> If somebody modifies the decoder/releasing logic, they must also change the way `trySingleRelease` works without breaking the entire API, so I believe it's fine merging this PR. What do you think?

It's ok. ~~Anyway, it's the forks that will end up going wrong, not Sonar itself.~~

**Comment by jonesdevelopment** [comment]
I don't think it'll cause any issues since we're replacing the decoder and encoder either way. The login packet is not even received by the server. The only way this could be "incompatible" is when the fork modified `trySingleRelease` in a way where it does not do the releasing anymore.

I'm testing it with some forks right now. I'll merge this tomorrow when I have a clear mind. Thanks a lot for your recent contributions btw.; I really appreciate it @FallenCrystal.

**Comment by jonesdevelopment** [comment]
This seems to work on normal BungeeCord and an old FlameCord fork I found on the internet: [MangoCord](<https://github.com/LuciaNishimiya/MangoCord>).
